### PR TITLE
Add node impl

### PR DESCRIPTION
**Pull request by cbrewster**
We switched from bun to node internally, so let's make sure were testing against what we're running in production.

### CODE REVIEW

**Comment by cbrewster** [comment]
Current dependencies on/for this PR:

* master:
  * **PR #13**
    * **PR #14** 👈

This comment was autogenerated by Freephite.

**Review by jackyzha0 — APPROVED** [review]
imo we should keep the bun folder around for if/when we go back and just make a new node folder (also we should delete `bun.lockb` in the node folder)

**Comment by cbrewster** [comment]
Is there a way we can share the implementations of the server & client between the two? Or does it make sense to have them just be duplicates?

**Comment by jackyzha0** [comment]
we can probably make a lib folder and put the actual impl there but imo its fine to duplicate for this :P

**Pull request merged**
